### ISSUE TITLE
remember button assigned

### ISSUE THREAD

**Issue by nicolgit** [50ButtonsEach/android-background-example#2]
in the sample here, on app start, the application have to select a button to use. after that, you are able to use the button inside the application. perfect.

Is there any way to "remember" the selection, so that at setup time the app is associated to the button, but since that moment **I can open and close the app all the times I need but I do not to remake a paring**?

thank you!

**Comment by Emill** [comment]
That is exactly what it does now.
When you call button.registerListenForBroadcast you tell the Flic app to send an intent to this app. If this app is currently not running, the Android system will start it up and then deliver the message.

**Comment by nicolgit** [comment]
Hi Emil, I have done some test, and it looks like that after a reboot, the link is lost. even if I open the app, events don't arrive. After I have clicked on "grab button" the app re-start to receive "flics". So the question is how to automate the connection on app start, without to click on grab button? 

thank you for your cool gadget,
N

**Comment by nicolgit** [comment]
Hi Emil, nay news on this issue? am I doing something wrong or you have any help?

**Comment by nicolgit** [comment]
hi @Emill any news on this?
